services:
  backend:
    build:
      context: .  # Root directory
      dockerfile: loan_api/Dockerfile
    container_name: smartloanpred-backend
    ports:
      - "8000:8000"
    volumes:
     - ./data:/app/loan_api/data
     -  backend-logs:/app_logs
     - ./loan_api/ModelFiles:/app/loan_api/ModelFiles
     - ./Rag_files:/app/Rag_files
     - chroma-db:/app/Rag_files/chroma_db
    working_dir: /app/loan_api
    environment:
      - GOOGLE_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - .env
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/chatbot/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: smartloanpred-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile : Dockerfile
    container_name: smartloanpred-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

  reverse-proxy:
    image: nginx:stable
    ports:
      - "80:80"
 
    depends_on:
      - backend
      - frontend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
  backend-logs:
  ollama-data:
  chroma-db:
