

dagshub: 
      repo_owner : "ajitkumarsenthil5"
      repo_name : "Loan_Approval_logs"
      use_mlflow : true 
      mlflow_uri: "https://dagshub.com/ajitkumarsenthil5/Loan_Approval_logs.mlflow"


mlflow: 
      set_experiment : "Loan_Approval_ML"
      set_experiment_1 : "Loan_classfication_models"
      set_experiment_2 : "PCA_Loan_approval"
      set_experiment_3 : "PCA custom experiment with Logistic Regression"
      set_experiment_4 : "PCA custom experiment with Ridge Classification"
      set_experiment_5 : "PCA custom experiment with XGBOOST"

feature_selection:
            threshold : 0.85
            variance_threshold : 0.0
            top_k : 10 

Pca_feature_parameters: 
                  n_components : 4
                  

llm:
      temperature : 0.6  # Balanced: natural and helpful responses
      model : "llama3.2"
      num_predict: 500   # Allow complete, detailed answers
      num_ctx: 4096      # Large context window for full history
      top_k: 50          # More diverse sampling
      top_p: 0.9         # Natural language flow


