

dagshub: 
      repo_owner : "ajitkumarsenthil5"
      repo_name : "Loan_Approval_logs"
      use_mlflow : true 
      mlflow_uri: "https://dagshub.com/ajitkumarsenthil5/Loan_Approval_logs.mlflow"


mlflow: 
      set_experiment : "Loan_Approval_ML"
      set_experiment_1 : "Loan_classfication_models"
      set_experiment_2 : "PCA_Loan_approval"
      set_experiment_3 : "PCA with Hybrid experiment"

feature_selection:
            threshold : 0.85
            variance_threshold : 0.0
            top_k : 10 

Pca_feature_parameters: 
                  n_components : 12
                  

